### ISSUE TITLE
Lỗi

### ISSUE THREAD

**Issue by lehuukhoa** [uetchatbot/chatbot-ws#1]
2017-07-07T10:28:02.492618+00:00 app[web.1]: /app/app/controllers/fb/webhook.js:11
2017-07-07T10:28:02.492628+00:00 app[web.1]: let WEBHOOK_TOKEN = config('WEBHOOK_TOKEN') || '';
2017-07-07T10:28:02.492629+00:00 app[web.1]:                     ^
2017-07-07T10:28:02.492631+00:00 app[web.1]: 
2017-07-07T10:28:02.492631+00:00 app[web.1]: ReferenceError: config is not defined
2017-07-07T10:28:02.492632+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/fb/webhook.js:11:21)
2017-07-07T10:28:02.492633+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-07-07T10:28:02.492634+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-07-07T10:28:02.492635+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-07-07T10:28:02.492635+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-07-07T10:28:02.492636+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-07-07T10:28:02.492637+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-07-07T10:28:02.492637+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-07-07T10:28:02.492638+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/index.js:4:14)
2017-07-07T10:28:02.492638+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-07-07T10:28:02.492639+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-07-07T10:28:02.492640+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-07-07T10:28:02.492640+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-07-07T10:28:02.492641+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-07-07T10:28:02.492642+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-07-07T10:28:02.492642+00:00 app[web.1]:     at require (internal/module.js:20:19)

**Comment by minhnt95** [comment]
Lỗi do config trong controller chưa khởi tạo, đã được fix trên master :D
