### ISSUE TITLE
Lỗi này là gì :D

### ISSUE THREAD

**Issue by lehuukhoa** [uetchatbot/chatbot-ws#2]
2017-07-08T03:06:22.331171+00:00 heroku[web.1]: Starting process with command `npm start`
2017-07-08T03:06:26.066305+00:00 app[web.1]: 
2017-07-08T03:06:26.066323+00:00 app[web.1]: > uetchatbot-ws@1.0.0 prestart /app
2017-07-08T03:06:26.066324+00:00 app[web.1]: > npm install
2017-07-08T03:06:26.066324+00:00 app[web.1]: 
2017-07-08T03:06:28.628020+00:00 app[web.1]: npm WARN bookshelf@0.10.3 requires a peer of knex@>=0.6.10 <0.13.0 but none was installed.
2017-07-08T03:06:28.650242+00:00 app[web.1]: 
2017-07-08T03:06:28.650245+00:00 app[web.1]: > uetchatbot-ws@1.0.0 start /app
2017-07-08T03:06:28.650246+00:00 app[web.1]: > node index.js
2017-07-08T03:06:28.650246+00:00 app[web.1]: 
2017-07-08T03:06:30.043944+00:00 app[web.1]: Server running at: http://localhost:6969
2017-07-08T03:06:31.001437+00:00 app[web.1]: { Error: connect ECONNREFUSED 127.0.0.1:3306
2017-07-08T03:06:31.001451+00:00 app[web.1]:     at Object.exports._errnoException (util.js:1018:11)
2017-07-08T03:06:31.001452+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:1041:20)
2017-07-08T03:06:31.001453+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
2017-07-08T03:06:31.001453+00:00 app[web.1]:     --------------------
2017-07-08T03:06:31.001454+00:00 app[web.1]:     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:141:48)
2017-07-08T03:06:31.001455+00:00 app[web.1]:     at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:52:41)
2017-07-08T03:06:31.001455+00:00 app[web.1]:     at Connection.connect (/app/node_modules/mysql/lib/Connection.js:130:18)
2017-07-08T03:06:31.001456+00:00 app[web.1]:     at /app/node_modules/knex/lib/dialects/mysql/index.js:106:18
2017-07-08T03:06:31.001456+00:00 app[web.1]:     at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:300:9)
2017-07-08T03:06:31.001457+00:00 app[web.1]:     at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
2017-07-08T03:06:31.001457+00:00 app[web.1]:     at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2017-07-08T03:06:31.001460+00:00 app[web.1]:     at Client_MySQL.acquireRawConnection (/app/node_modules/knex/lib/dialects/mysql/index.js:104:12)
2017-07-08T03:06:31.001461+00:00 app[web.1]:     at Object.create (/app/node_modules/knex/lib/client.js:239:16)
2017-07-08T03:06:31.001462+00:00 app[web.1]:     at Pool._createResource (/app/node_modules/generic-pool/lib/generic-pool.js:354:17)
2017-07-08T03:06:31.001462+00:00 app[web.1]:     at Pool.dispense [as _dispense] (/app/node_modules/generic-pool/lib/generic-pool.js:314:10)
2017-07-08T03:06:31.001463+00:00 app[web.1]:     at Pool.acquire (/app/node_modules/generic-pool/lib/generic-pool.js:436:8)
2017-07-08T03:06:31.001463+00:00 app[web.1]:     at /app/node_modules/knex/lib/client.js:289:19
2017-07-08T03:06:31.001464+00:00 app[web.1]:     at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:300:9)
2017-07-08T03:06:31.001464+00:00 app[web.1]:     at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
2017-07-08T03:06:31.001465+00:00 app[web.1]:     at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
2017-07-08T03:06:31.001465+00:00 app[web.1]:   code: 'ECONNREFUSED',
2017-07-08T03:06:31.001465+00:00 app[web.1]:   errno: 'ECONNREFUSED',
2017-07-08T03:06:31.001466+00:00 app[web.1]:   syscall: 'connect',
2017-07-08T03:06:31.001466+00:00 app[web.1]:   address: '127.0.0.1',
2017-07-08T03:06:31.001467+00:00 app[web.1]:   port: 3306,
2017-07-08T03:06:31.001467+00:00 app[web.1]:   fatal: true }

**Comment by bqcuong** [comment]
Error: connect ECONNREFUSED 127.0.0.1:3306

**Comment by lehuukhoa** [comment]
fix sao bạn

**Comment by bqcuong** [comment]
có thể là do bạn chưa cấu hình đúng database

**Comment by lehuukhoa** [comment]
Mình xong cấu hình đúng database. Giờ mình tạo database gì ko ? 
Thấy lỗi 
2017-07-08T04:34:13.316775+00:00 app[web.1]: { Error: ER_NO_SUCH_TABLE: Table 'heroku_02375f3de4989cf.users' doesn't exist
2017-07-08T04:34:13.316795+00:00 app[web.1]:     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
2017-07-08T04:34:13.316796+00:00 app[web.1]:     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
2017-07-08T04:34:13.316797+00:00 app[web.1]:     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23)
2017-07-08T04:34:13.316797+00:00 app[web.1]:     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:75:12)
2017-07-08T04:34:13.316798+00:00 app[web.1]:     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2017-07-08T04:34:13.316799+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:103:28)
2017-07-08T04:34:13.316800+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-07-08T04:34:13.316800+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-07-08T04:34:13.316801+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2017-07-08T04:34:13.316802+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:134:10)
2017-07-08T04:34:13.316802+00:00 app[web.1]:     at TCP.onread (net.js:547:20)

**Comment by minhnt95** [comment]
@lehuukhoa : cấu trúc database của chatbot được generate tự động bởi knex (bạn đọc lại readme.md sẽ thấy). Khi khởi động lần đầu phải chạy `npm run db` để tạo db trước. 
Lỗi này của bạn do chưa tạo db.
