### ISSUE TITLE
Lỗi :<

### ISSUE THREAD

**Issue by nghminh163** [uetchatbot/chatbot-ws#4]
Khi em sử dụng câu lệnh npm run database thì bị lỗi ntn ạ

> uetchatbot-ws@1.0.0 database /home/ubuntu/workspace
> knex migrate:latest

Using environment: development
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)
    --------------------
    at Protocol._enqueue (/home/ubuntu/workspace/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/ubuntu/workspace/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/home/ubuntu/workspace/node_modules/mysql/lib/Connection.js:130:18)
    at /home/ubuntu/workspace/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/home/ubuntu/workspace/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/ubuntu/workspace/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/ubuntu/workspace/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/home/ubuntu/workspace/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/home/ubuntu/workspace/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/home/ubuntu/workspace/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/home/ubuntu/workspace/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/home/ubuntu/workspace/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MySQL.initializePool (/home/ubuntu/workspace/node_modules/knex/lib/client.js:269:17)
    at Client_MySQL.Client (/home/ubuntu/workspace/node_modules/knex/lib/client.js:116:12)
    at new Client_MySQL (/home/ubuntu/workspace/node_modules/knex/lib/dialects/mysql/index.js:62:20)
    at Knex (/home/ubuntu/workspace/node_modules/knex/lib/index.js:60:34)

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "database"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! uetchatbot-ws@1.0.0 database: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uetchatbot-ws@1.0.0 database script 'knex migrate:latest'.
npm ERR! This is most likely a problem with the uetchatbot-ws package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex migrate:latest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uetchatbot-ws
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls uetchatbot-ws
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
Các anh cho em xin cách fix với ạ. Em cảm ơn ạ

**Comment by bqcuong** [comment]
`Error: connect ECONNREFUSED 127.0.0.1:3306`
Bạn kiểm tra tới MySQL nhé
