### ISSUE TITLE
Lỗi khi npm start

### ISSUE THREAD

**Issue by nghminh163** [uetchatbot/chatbot-ws#5]
Khi em dùng nhập npm start thì nó bị lỗi như sau ạ

> uetchatbot-ws@1.0.0 prestart /home/ubuntu/workspace
> npm install

npm WARN package.json Dependency 'knex' exists in both dependencies and devDependencies, using 'knex@^0.13.0' from dependencies

> uetchatbot-ws@1.0.0 start /home/ubuntu/workspace
> node index.js

/home/ubuntu/workspace/config/bookshelft.js:3
let knex = require('knex')({
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/models/Models.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "start"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! uetchatbot-ws@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uetchatbot-ws@1.0.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the uetchatbot-ws package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uetchatbot-ws
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls uetchatbot-ws
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

Các anh có thể cho em biết nguyên nhân lỗi và cách fix được không ạ? Em cảm ơn

**Comment by minhnt95** [comment]
Lỗi này xuất hiện khi sử dụng cú pháp es6 ngoài phạm vi 'strict mode' . 
Có 2 cách để fix:
1. Thêm anotation `'use strict'` vào đầu tệp /home/ubuntu/workspace/config/bookshelft.js
2. Nâng cấp phiên bản bản nodeJs lên > 6.0

Hồi âm lại nếu em sửa thành công nhé :D

**Comment by nghminh163** [comment]
Em rất cảm ơn anh khi anh đã phản hồi lại cho em nhanh chóng
Khi em tiến anh fix lỗi theo cả 2 cách trên thì lại nhận đc 1 bug khác
> uetchatbot-ws@1.0.0 prestart /home/ubuntu/workspace
> npm install

npm WARN package.json Dependency 'knex' exists in both dependencies and devDependencies, using 'knex@^0.13.0' from dependencies

> uetchatbot-ws@1.0.0 start /home/ubuntu/workspace
> node index.js

/home/ubuntu/workspace/app/services/database.js:46
module.exports.deleteUsers = function (...lhs_fb_ids) {
                                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/app/services/webhook.js:9:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/app/services/index.js:4:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/scheduler/match-users.js:3:17)

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "start"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! uetchatbot-ws@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uetchatbot-ws@1.0.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the uetchatbot-ws package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uetchatbot-ws
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls uetchatbot-ws
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by minhnt95** [comment]
cú pháp '...' báo lỗi trên là 'spread operator' (cũng là 1 tính năng của es6), e có thể tìm hiểu thêm ở đây: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator
Có thể em sẽ phải update bản nodejs hiện tại lên v6.11(LTS) để chạy được source code chatbot.
a đọc log của e thì thấy bản nodejs của e đang là v4.7.3.

**Comment by nghminh163** [comment]
Vâng ạ em cảm ơn
